- docs/Components/ROS2/ROS2TopicList/index.md
- docs/Components/Traffic/RandomTraffic/RandomTrafficSimulator/index.md
Fixed broken links, may be caused by structural changes in the document
> Fix broken link

- .github/workflows/documentation_link_check.yml
This pull request adds a GitHub actions workflow for link checking in markdown or html file!
TODO(@mackierx111 ) : Add GitHub Token to secrets of this repository
reference : https://github.com/tier4/scenario_simulator_v2/blob/master/.github/workflows/DocumentationLinkCheck.yaml
> Add link checking workflow for document

- docs/Components/Sensors/CameraSensor/index.md
> fix: markdown table

- Assets/AWSIM/Prefabs/Environments/Nishishinjuku/Nishishinjuku RandomTraffic.prefab
- Assets/AWSIM/Prefabs/Environments/Nishishinjuku/Nishishinjuku.prefab
> Tokyo Shinjuku MGRS Grid zone

- docs/GettingStarted/QuickStartDemo/index.md
Signed-off-by: alan.meng <alan.meng@autocore.ai>
> add example video

- docs/GettingStarted/QuickStartDemo/index.md
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
> docs: fix galactic document

- .github/workflows/buildtest.yaml
- docs/Components/ROS2/AddCustomROS2MessageType/index.md
- docs/GettingStarted/QuickStartDemo/index.md
- docs/GettingStarted/SetupUnityProject/index.md
> docs: update document from galactic to humble

- docs/DeveloperGuide/HowToContribute/index.md
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
I update the contribution guideline.
I reffered to https://autowarefoundation.github.io/autoware-documentation/main/contributing/
> feature: update contribution guideline

- docs/GettingStarted/QuickStartDemo/index.md
Add `source install/setup.bash`.  
Without this, you might fail to execute
`ros2 topic pub /autoware/engage autoware_auto_vehicle_msgs/msg/Engage '{engage: True}' -1`
> docs: update readme

- ProjectSettings/TagManager.asset
- ProjectSettings/TimeManager.asset
- changed fixed timestep from 100FPS to 60FPS
- added visualization layer
> Performance Improvements: Physics step and layer

- Assets/AWSIM/Scripts/Lanelet/Core/LaneletMap.cs
Removed forcing the ID regeneration when the provided ID is negative.
> Lanelet negative IDs support

- Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
- Assets/AWSIM/Scenes/Main/AutowareSimulation/AutowareSimulation.cs
- Assets/AWSIM/Scenes/Main/AutowareSimulation/config.json
Add possibility to set initial EGO position and rotation from JSON config file
> Add ego initial position and rotation from json config

- .gitignore
> chore(.gitignore): add /.idea/

- Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
- Assets/RGLUnityPlugin/Scripts/SceneManager.cs
Fix to the bug described [here](https://github.com/autowarefoundation/autoware-projects/issues/67#issuecomment-1705496973).
> Fix RGL scene synchronization when FixedUpdate is called more frequently than Update

- Assets/RGLUnityPlugin/Scripts/LidarUdpPublisher.cs
I added an IP address validation for LidarUdpPublisher
> Added IP address validation for source IP of LidarUdpPublisher

- Assets/AWSIM/Scripts/Sensors/GnssNavSat/GnssNavSat.cs
This commit adds GPS sensor and publishes [sensor_msgs::NavSatFix](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/NavSatFix.html) as well as velocity in the form of Vector3Stamped. 
It assumes that the base of robot is `base_link`, the reported NavSatFix message is reporting the absolute position of `base_link`
> Add GNSS NavSat Sensor

- Assets/AWSIM/Prefabs/UI/MainCameraView.prefab
- Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
- Assets/AWSIM/Scripts/FollowCamera.cs
- docs/Components/Vehicle/FollowCamera/index.md
Improved camera rotated around feature.
Changes:
- Add fixed camera view (left, right, front, back),
- Change usability, so to adjust camera view the `Left Shift` must be held,
- Update to documentation.
> Improved camera rotate around feature

- Assets/AWSIM/Models/Sensors/Radar DRVEGRD 169/Radar_Collider.fbx.meta
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiAT128E2X.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandar128E4X.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandar40P.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandarXT32.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiQT128C2X.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/OusterOS1-64.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/SmartmicroDRVEGRD169.prefab
- Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs
- Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNodeSequence.cs
- Assets/RGLUnityPlugin/Scripts/RadarModels/RadarConfiguration.cs
- Assets/RGLUnityPlugin/Scripts/RadarModels/RadarNoiseParams.cs
- Assets/RGLUnityPlugin/Scripts/RadarSensor.cs
PR contains:
- radar power and noise level integration
- radar parameters fine-tuning
- fix to mesh collider (must be convex to work with non-kinematic rigid body)
- fix to node sequences
- bug discovered after `RglLidarPublisher` component refactor
> Minor fixes to radar parameters, 3d models and node sequence

- docs/Components/Clock/ClockPublisher/index.md
Documentation improvement in clock publisher section. 
- updated of time sources description.
> Updated description of time sources

- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiAT128E2X.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandar128E4X.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandar40P.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandarQT64.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandarXT32.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiQT128C2X.prefab
- Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/OusterOS1-64.prefab
- Assets/RGLUnityPlugin/Scripts/LidarModels/LaserArrayLibrary.cs
- Assets/RGLUnityPlugin/Scripts/LidarModels/LidarConfigurationLibrary.cs
The parameters of the LiDAR models have been verified to match manuals
> Fix LiDAR models to match the manuals

- Assets/Tests/EditMode/Lanelet/LaneletTest.cs
- Assets/Tests/PlayMode/Traffic/TrafficTest.cs
Improved comments/description of integration tests for:
- Lanelet importer tests,
- Traffic Manager tests.
> Improved tests description

- Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
Related to https://github.com/autowarefoundation/AWSIM-Labs/issues/104
> Sync LiDAR's timer on enable to achieve the best performance

- Assets/Awsim/Scripts/Entity/Vehicle/AccelVehicle/Input/AccelVehicleControlModeBasedInputter.cs
- Assets/Awsim/Scripts/Entity/Vehicle/AccelVehicle/Input/AccelVehicleKeyboardInput.cs
- Assets/Awsim/Scripts/Entity/Vehicle/AccelVehicle/Input/AccelVehicleLogitechG29Input.cs
- Assets/Awsim/Scripts/Entity/Vehicle/AccelVehicle/Input/AccelVehicleRos2Input.cs
- Assets/Awsim/Scripts/Entity/Vehicle/AccelVehicle/Input/IAccelVehicleInput.cs
- docs/DeveloperGuide/Layer/Entity/Vehicle/AccelVehicle/index.md
> Enable switching the ControlMode to AUTONOMOUS from the device

- docs/DeveloperGuide/Layer/Usecase/PcdGeneration/index.md
- docs/DeveloperGuide/Layer/Usecase/ScenarioSimulatorConnection/index.md
- docs/DeveloperGuide/Layer/Usecase/TrafficSimulation/index.md
- mkdocs.yml
Jira: https://tier4.atlassian.net/browse/T4DEV-30082
Documents:
- [AwsimRvizPlugins](https://github.com/tier4/AWSIM/blob/docs/format_usecase/docs/DeveloperGuide/Layer/Usecase/AwsimRvizPlugins/index.md)
- [ScenarioSimulatorConnection](https://github.com/tier4/AWSIM/blob/docs/format_usecase/docs/DeveloperGuide/Layer/Usecase/ScenarioSimulatorConnection/index.md)
- [TrafficSimulation](https://github.com/tier4/AWSIM/blob/docs/format_usecase/docs/DeveloperGuide/Layer/Usecase/TrafficSimulation/index.md)
- fix typo ([#1f8ee18](https://github.com/tier4/AWSIM/pull/433/commits/1f8ee1809acb6bec055ef55fdef43a7aaf67eb04))
- change `ScenarioSimulatorConnection/Overview` to Table from dot list ([#61998df](https://github.com/tier4/AWSIM/pull/433/commits/61998dfa62214e1afc3db258637de8b86bc7a1d4))
- add …
> docs: unify expression of `Layer/Usecase` documents

- .github/pull_request_template.md
- docs/DeveloperGuide/HowToContribute/index.md
- Add License for contributer in `HowToContribute`
- Add Check list in PR template about License
Jira: https://tier4.atlassian.net/browse/T4DEV-21232
> docs: add description about License for contributer

- Assets/Awsim/Prefabs/Entity/Npc/Vehicle/Urp/Hatchback.prefab
- Assets/Awsim/Prefabs/Entity/Npc/Vehicle/Urp/SmallCar.prefab
- Assets/Awsim/Prefabs/Entity/Npc/Vehicle/Urp/Taxi.prefab
- Assets/Awsim/Prefabs/Entity/Npc/Vehicle/Urp/Truck_2t.prefab
- Assets/Awsim/Prefabs/Entity/Npc/Vehicle/Urp/Van.prefab
Jira: https://tier4.atlassian.net/browse/T4DEV-30081
> fix: remove unnecessary component from `Prefabs/Entity/Npc/Vehicle/Urp/*`
