tier4/AWSIM

docs/GettingStarted/QuickStartDemo/index.md
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
With Humble, Autoware should use the `awsim-stable` branch, but the docs is wrong. 
I apologize for the inconvenience caused by my big mistake.
=> docs: fix to use awsim-stable branch

mkdocs.yml
The footer navigation is gone.
The major version of mkdocs material has been upgraded and a new configuration item has been added.
https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#navigation
This PR will enable the above settings and behave the same as before
=> docs: apply navigation.footer

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/task.yaml
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
I add issue template to 
- clarify what the issue is
- support what information should be written
- share the knowledge with AWF
Issues in AWSIM will be only for 
- bug reports  
- feature request
- task 
while the question will be discussed in [AWF discussion](https://github.com/orgs/autowarefoundation/discussions/).
The picture shows the image when you try to create the Issue.
You can try this with [my prototype](https://github.com/shmpwk/AWSIM/issues/new/choose).
Note that this PR partially comes from https://github.com/autowarefoundation/autoware/commit/9581b82ac8a91877e6ed2a00253d3f122fb39270
I will add contribution guidline to describe how to use them https://github.com/tier4/AWSIM/pull/83.
=> feature: add issue template

Assets/AWSIM/Prefabs/NPCs/Pedestrians/humanElegant.prefab
When pedestrians are out of the camera, their models are not updated. It affects the lidar point cloud, which is inconsistent with reality. I have changed the prefab to "Always Animate".
=> Always animate pedestrians

Assets/AWSIM/Scenes/Main/AutowareSimulation.unity, Assets/AWSIM/Scripts/NPCs/Vehicles/NPCVehicle.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/NPCVehicleConfig.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/NPCVehicleInternalState.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/NPCVehicleSpawner.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/Steps/NPCVehicleCognitionStep.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/Steps/NPCVehicleControlStep.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/Steps/NPCVehicleDecisionStep.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/Steps/NPCVehicleVisualizationStep.cs, Assets/AWSIM/Scripts/RandomTraffic/RandomTrafficSimulator.cs
I’ve noticed some issues, I have suggestions for consideration, I believe they can make the behavior of RandomTraffic better.
A more detailed description can be read [here]( https://tier4.atlassian.net/browse/AJD-708?focusedCommentId=115467).
- Numerous problems with yielding priority, especially when turning left, regardless of the intersection. Vehicles sometimes block each other, passing through each other and even disappearing into one another.
- The problem occurs whenever the vehicle (2) to be yielded enters the intersection and vehicle (1) is already there - (2) is completely ignored by  - example:
- The presence or absence of a additional StopLine at an intersection (not before) is not related to this.
- Vehicles stop to yield the right of way only before an intersection - more …
=> Random traffic slightly improve

docs/GettingStarted/QuickStartDemo/index.md
Bumping requirements to CUDA 11.7 (minimal version supported on Ubuntu 22)
=> Update Nvidia Driver requirements

Assets/Ros2ForUnity/Scripts/PostInstall.cs
When building AWSIM, Unity skips versioned libraries (e.g., libExample.so.1.2.3). It is required to copy them manually.
=> Copy versioned r2fu libraries when building AWSIM

Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/NPCVehicleInternalState.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/Steps/NPCVehicleCognitionStep.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/Steps/NPCVehicleDecisionStep.cs
If the vehicle spawns close to the already existing vehicle, and this distance is smaller than `MinFrontVehicleDistance`, then the `distanceToStopPointByFrontVehicle` is in infinite, and spawned vehicle ignores everything in front of him.
This [commit](https://github.com/tier4/AWSIM/commit/2a7f8c4fd376b7f1fee9601c94433bb2536033db) fixes this problem - the distance to the front of vehicles is calculated correctly.
I also corrected some typos.
https://github.com/tier4/AWSIM/assets/121798334/09eb8fab-4f7e-4335-ba13-9f4a6d35c50f
https://github.com/tier4/AWSIM/assets/121798334/7fed7157-8da4-4e0e-8967-3379429bea3e
=> fix(random_traffic): fix spawn issue - distance_to_stop

Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandar40P.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandarQT64.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/OusterOS1-64.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/VelodyneVLP16.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/VelodyneVLP32C.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/VelodyneVLS128.prefab, Assets/RGLUnityPlugin/Scripts/LidarModels/LidarConfiguration.cs, Assets/RGLUnityPlugin/Scripts/LidarModels/LidarConfigurationLibrary.cs
- Added limits to horizontal angles (-360 to 360).
- Added horizontal range validation (cannot exceed 360 degrees).
- Fixed start angles of Hesai, Ouster, and Velodyne lidars to match their real-world configuration.
- Replaced horizontal steps GUI parameter with horizontal resolution.
=> Improve lidar configuration

mkdocs.yml
The LaneletBoundsVisualizer document was not showing up in the AWSIM Documentation page since I forgot to edit the mkdocs.yml in the previous Pull Request.
The problem is solved with this pull request.
=> docs: add LaneletBoundsVisualizer document

Assets/RGLUnityPlugin/Scripts/LidarModels/LidarConfiguration.cs
Float to int conversion drops the fractional part of the number. For some nicely divisible values, it understates the result (e.g., 0.2 degrees of resolution: 360 / 0.2 = 1800, but it returns 1799). I used `Math.Round` to fix it.
=> Fix horizontal steps calculation from the horizontal resolution

docs/GettingStarted/SetupUnityProject/index.md
The current link for `openssl` (https://tier4.github.io/AWSIM/GettingStarted/SetupUnityProject/) does not work.
```
▶ wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.12_amd64.deb
--2023-06-07 22:07:01--  http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.12_amd64.deb
Resolving security.ubuntu.com (security.ubuntu.com)... 2620:2d:4000:1::16, 2620:2d:4000:1::19, 2001:67c:1562::15, ...
Connecting to security.ubuntu.com (security.ubuntu.com)|2620:2d:4000:1::16|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-07 22:07:01 ERROR 404: Not Found
```
It looks like the version was recently updated from `12` to `13`. This PR simply updates the version number in the link.
=> Fix broken link to OpenSSL

Assets/RGLUnityPlugin/Scripts/LidarModels/LaserArray.cs, Assets/RGLUnityPlugin/Scripts/LidarModels/LidarConfiguration.cs, Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
Before this PR, laser poses were generated in the lidar game object origin with the translation to match LiDAR origin (the center of measurement vertical linear offset). It caused wrong distance calculation.
Now, laser poses are generated without respecting `centerOfMeasurementVerticalLinearOffsetMm`, and that transform (from the game object to the LiDAR origin) is applied when setting the pose of the LiDAR.
=> Fix laser poses to be generated in the LiDAR origin

Assets/RGLUnityPlugin/Scripts/SceneManager.cs
Removed LINQ and lambdas from initialization of thisFrameGOs variable. Performance tested on AWSIM/Scenes/Samples/LidarSkinnedStress scene since it provides a stable number of entities. The performance of the "Find changes and make TODO list" profiler section improved drastically from taking 21 ms to 9 ms on my machine:
Lenovo Legion Laptop
Processor: 1x 10th Generation Intel® Core™ i7-10750H Processor(Core™ i7-10750H)
Graphics: 1x NVIDIA®GeForce RTX™2070 SUPER™
I tried removing LINQ and lambdas from all other parts of SceneManager.cs, but this offered no noticeable performance improvements, so I decided to keep the old code for readability reasons.
=> Performance increase for RGLUnityPlugin by reducing garbage collection

Assets/AWSIM/Prefabs/Sensors/OdometrySensor.prefab, Assets/AWSIM/Prefabs/Sensors/OdometrySensor.prefab.meta, Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab, Assets/AWSIM/Scenes/Main/AutowareSimulation.unity, Assets/AWSIM/Scripts/Sensors/Odometry.meta, Assets/AWSIM/Scripts/Sensors/Odometry/OdometryRos2Publisher.cs, Assets/AWSIM/Scripts/Sensors/Odometry/OdometryRos2Publisher.cs.meta, Assets/AWSIM/Scripts/Sensors/Odometry/OdometrySensor.cs, Assets/AWSIM/Scripts/Sensors/Odometry/OdometrySensor.cs.meta
This PR resolve https://github.com/tier4/AWSIM/issues/177
- add odometry sensor prefab
- add odometry prefab to unity scene  https://docs.ros2.org/foxy/api/nav_msgs/msg/Odometry.html
- topic is `/awsim/ground_truth/localization/kinematic_state`
tested with main scene
=> feat(odometry_sensor): add ground truth odometry to Unity scene

Assets/RGLUnityPlugin/README.md, Assets/RGLUnityPlugin/Scripts/LidarSensor.cs, Assets/RGLUnityPlugin/Scripts/PointCloudVisualization.cs, docs/Components/Sensors/LiDARSensor/AddNewLiDAR/index.md
Minor optimization.
Before PR: on every LiDAR's `Capture()` a slow function `GetComponent` was called to access `PointCloudVisualization` component.
Now, I have moved retrieving point cloud visualization data to `PointCloudVisualization` component. This change allowed us to get rid of `GetComponent` function.
=> Optimize PointCloudVisualization by reducing usage of GetComponent

ProjectSettings/HDRPProjectSettings.asset
This PR disables this window from popping up everytime the Unity Editor is opened.
=> chore: disable startup hdrp pop up in editor

Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLMeshObject.cs, Assets/RGLUnityPlugin/Scripts/SceneManager.cs
In the [issue](https://github.com/tier4/AWSIM/issues/199), some of the game objects on the scene don't have mesh assigned to them, which prevents RGLObjects from being created on them (an exception is thrown in the constructor of RGLObject). It causes the current Update to abort and process the same objects on the next Update (and this situation repeats indefinitely).
This PR wraps RGLObject creation into a try-catch block which skips game objects from which no RGLObject can be created.
=> Wrap RGLObject into try-catch to avoid processing the same objects endlessly

Assets/AWSIM/Scenes/Main/PointCloudMapping/Scripts/Mapper/RGLMappingAdapter.cs, Assets/AWSIM/Scripts/Sensors/LiDAR/PointCloudFormats.cs, Assets/AWSIM/Scripts/Sensors/LiDAR/RglLidarPublisher.cs, Assets/RGLUnityPlugin/Scripts/LidarSensor.cs, Assets/RGLUnityPlugin/Scripts/LidarUdpPublisher.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeTypes.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNodeSequence.cs, Assets/RGLUnityPlugin/Scripts/PointCloudVisualization.cs, Assets/RGLUnityPlugin/Scripts/SceneManager.cs
- Updated `RGLUnityPlugin` to work with [RGL v0.16.2](https://github.com/RobotecAI/RobotecGPULidar/releases/tag/v0.16.2)
- Minor fixes:
- `TimeSource` is set directly in `SceneManager` (it was performed in `RglLidarPublisher` previously)
- ROS2 topics are not created if `RglLidarPublisher` component is disabled
=> Upgrade RGL to v16

docs/Components/ROS2/ROS2ForUnity/index.md, docs/GettingStarted/SetupUnityProject/index.md
Added the information about sourcing ROS 2 when working with AWSIM.
=> ROS 2 sourcing policy in documentation

Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs
The latest ROS2 release is not working with the RGL standalone build.
RGLUnityPlugin should be running without sourcing ROS2 (the same as Ros2ForUnity plugin).
This PR adds an error message if running RGLUnityPlugin with sourced ROS2.
Related issue: https://github.com/tier4/AWSIM/issues/187
=> Warn user if running RGLUnityPlugin with sourced ROS2

Assets/AWSIM/Scripts/ROS/ClockPublisher.cs
This PR changes the functionality of the `/clock`. To make the clock's publishing frequency independent of the time scale.
Previously:
At timescale set to **1.0**; `/clock` publish at rate **100Hz**;  time difference between timestamps in messages equal to **10 ms**;
At timescale set to **0.1**; `/clock` publish at rate **10Hz**; time difference between timestamps in messages equal to **10 ms**;
New behavior:
At timescale **1.0** everything stays the same.
At timescale **0.1**; `/clock` publish at rate **100Hz**; time difference between timestamps in messages equal to **1ms**;
=> Made clock published independently from time scale

Assets/AWSIM/Prefabs/UI.meta, Assets/AWSIM/Prefabs/UI/MainCameraView.prefab, Assets/AWSIM/Prefabs/UI/MainCameraView.prefab.meta, Assets/AWSIM/Scripts/FollowCamera.cs, Assets/AWSIM/Scripts/UI/MainCameraViewUI.cs, Assets/AWSIM/Scripts/UI/MainCameraViewUI.cs.meta
**Intention:**
To add functionality to the main camera - `FollowCamera.cs` script to allow the user to rotate the camera around a specific target.
**Includes:**
- refactor of the existing `FollowCamera.cs `script,
- adding a new functionality to the main camera, that allows the user to rotate the camera around the target,
- adding an optional UI View - with hints on how to use it,
**How to use:**
- camera rotation around target can be activated by pressing the 'C' key on the keyboard - text info at the top of the screen will indicate if camera is ready to be rotate,
- use the numeric keypad to control the view of the main camera, in such way:
<ul>
- 'numkey 1' - to rotate left;
- 'numkey 3' - to rotate right;
- 'numkey 2' - to set the back view;
- 'numkey 8' - to set the front view;
- …
=> Feature: Main Camera Rotate Around

Assets/AWSIM/Scenes/Main/AutowareSimulation.unity, Assets/AWSIM/Scripts/Clock/Scripts/DotNetSystemTimeSource.cs, Assets/AWSIM/Scripts/Clock/Scripts/DotNetSystemTimeSource.cs.meta, Assets/AWSIM/Scripts/Clock/Scripts/TimeScaleProvider.cs, Assets/AWSIM/Scripts/Clock/Scripts/TimeScaleProvider.cs.meta, Assets/AWSIM/Scripts/Clock/Scripts/TimeSourceProvider.cs, Assets/AWSIM/Scripts/ROS/ClockPublisher.cs, Assets/AWSIM/Scripts/UI/DemoUI.cs
Clock publisher that works in a dedicated thread and it is time scale independent.
Time scale independent means:
- clock always publishes at the required frequency regardless of the the timescale value,
- time difference in messages timestamp is impacted by the time scale value.
The PR includes:
- clock publisher that start new `Clock Thread` and use this thread to publish time messages,
- time source `DotNetSystemTimeSource.cs` - thread-safe class for reading the .NET system time,
- `TimeScaleProvider` - class that provides and synchronizes timescale value between **clock** and **main threads**.
This PR also adds a `TimeSourceSelector` object to the main AWSIM scene, in order to select correct **TimeSource** to be used by the `SimulatorROS2Node`
=> Clock publisher works in dedeciated thread

Assets/AWSIM/Scripts/Environments/TrafficLight.cs
This feature allows more customisation of the traffic light shaders. For example, in the case of traffic lights constructed in such a way, that there is a single bulb for red and green. And, to create a digital twin of such a construction in AWSIM, a custom shader has to be designed.
The changes include:
- introduceing the new shader parameter in the `TrafficLight.cs` script: _**"_LightOn"**_
- setting the value of this parameter when the light bulb state changes,
This allows to move the critical implementation of the light behaviour to be moved to the shader instead of implementing it in `TrafficLight.cs.`
=> Added LightOn Shader Properties to Traffic Light

Assets/AWSIM/Scripts/Sensors/Camera/CameraSensorHolder.cs
This PR resolves https://github.com/tier4/AWSIM/issues/238
Evidence in the table below
Expected Hz| Before fix | After fix |
| -- | --- | --- | 
| 10| ![Screenshot_20240206_105031](https://github.com/tier4/AWSIM/assets/8416175/4107c33c-537f-4240-83e1-c58ff60c844f) | ![Screenshot_20240206_105341](https://github.com/tier4/AWSIM/assets/8416175/db9b7175-7335-4529-9692-ee5f16682412)  |
| 5 | ![Screenshot_20240206_105134](https://github.com/tier4/AWSIM/assets/8416175/f879a977-7287-438c-83ab-2b6224d5709d)  | ![Screenshot_20240206_105246](https://github.com/tier4/AWSIM/assets/8416175/cf5c8f72-1cfa-4cb6-ac21-581dafd0d576)  |
=> fix(camera): improve camera topic hz

Assets/RGLUnityPlugin/Scripts/LidarSensor.cs, Assets/RGLUnityPlugin/Scripts/LidarSnowManager.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNodeSequence.cs
This PR provides interface extension to the snow simulation feature. It adds the following widgets:
- checkbox DoSimulateEnergyLoss - switches between snow simulation methods - if false, the algorithm takes into account only the closest snowflake in the ray beam. If true, it takes into account all snowflakes in the ray beam and computes energy loss.
- slider SnowflakeOccupancyThreshold - Allows to ignore snowflakes that are less than given fraction of ray beam, as if they were transparent.
=> Integrate energy loss feature to lidar snow

Assets/AWSIM/Scripts/Editor/RandomTraffic/Environments/LaneletLoader/LaneletLoader.cs, Assets/AWSIM/Scripts/Environments/TrafficLightLaneletID.cs
Add warning if way id and relation id may be incorrectly assigned
Sample:
=> fix: add warning if way id and relation id may be incorrectly assigned

Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/VelodyneVLP16.prefab, Assets/AWSIM/Scripts/Editor/AWSIM.Editor.asmdef, Assets/AWSIM/Scripts/Editor/AWSIM.Editor.asmdef.meta, Assets/AWSIM/Scripts/Lanelet/Visualize/Editor/AWSIM.Editor.asmref, Assets/AWSIM/Scripts/Lanelet/Visualize/Editor/AWSIM.Editor.asmref.meta, Assets/AWSIM/Scripts/Vehicles/Editor/AWSIM.Editor.asmref, Assets/AWSIM/Scripts/Vehicles/Editor/AWSIM.Editor.asmref.meta
This PR provides two fixes:
- add assemblies for Editor folders. Right now on the `main` branch, the binary can't be built due to an issue with the assemblies. The PR resolves this issue.
- update velodyne vlp16 prefab. Right now on `main` the AWSIM does not work with Autoware. The PR resolves this issue.
=> fix: fix assemblies

Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiAT128E2X.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandar128E4X.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandar40P.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandarQT64.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiPandarXT32.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/HesaiQT128C2X.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/OusterOS1-64.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/VelodyneVLP16.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/VelodyneVLP32C.prefab, Assets/AWSIM/Prefabs/Sensors/RobotecGPULidars/VelodyneVLS128.prefab
This PR fixes prefabs after introducing validation of the LiDAR configuration (https://github.com/tier4/AWSIM/pull/294)
The configuration interface has changed and old prefabs couldn't be loaded properly.
=> Update prefabs of the LiDARs after configuration interface changes

Assets/Tests/PlayMode/Sensors/SensorsTest.cs, Assets/Tests/PlayMode/Sensors/SensorsTest.unity, docs/ProjectGuide/Testing/index.md
This PR:
- restores the regression test for LiDAR (it was deleted due to compilation errors after refactoring `RglLidarPublisher` component)
- adds the regression test for Radar
The changes are identical as proposed in [this PR](https://github.com/tier4/AWSIM/pull/282) but I decided to close it due to non-trivial merging conflicts.
=> Regression tests for LiDAR and Radar

Assets/AWSIM/Prefabs/ScenarioSimulatorConnector/ScenarioSimulatorConnector.prefab
Missing `sign_board` causes the following issue
This PR fixes the issue by adding `sign_board` to entity prefab list
=> fix: ScenarioSimylatorConnector prefab

Assets/Tests/PlayMode/Traffic/TrafficTest.unity
=> fix: update missing prefab in TrafficTest

Assets/AWSIM/Scripts/Environments/Environment.cs, Assets/AWSIM/Scripts/GeoCoordinate.meta, Assets/AWSIM/Scripts/GeoCoordinate/GeoCoordinate.cs, Assets/AWSIM/Scripts/GeoCoordinate/GeoCoordinate.cs.meta, Assets/AWSIM/Scripts/GeoCoordinate/GeoCoordinateConverter.cs, Assets/AWSIM/Scripts/GeoCoordinate/GeoCoordinateConverter.cs.meta, Assets/AWSIM/Scripts/Sensors/Gnss/GnssRos2NavSatFixPublisher.cs, Assets/AWSIM/Scripts/Sensors/Gnss/GnssRos2NavSatFixPublisher.cs.meta, Assets/AWSIM/Scripts/Sensors/Gnss/GnssSensor.cs
- add geographic coordinate calculation scripts (`GeoCoordinate.cs`, `GeoCoordinateConverter.cs`)
- add parameter that can be set from the Inspector window for geographic calculation to `Environment.cs`
- add `GnssRos2NavSatFixPublisher.cs` to publish `sensor_msgs/NavSatFix` topic
To minimize impact on other projects, it's implemented separately from the existing GnssRos2Publisher.
The motivation is to test `eagleye` at runtime with AWSIM.
ref link:
Geographpic coordinate calculations are implemented with reference to the following sites
=> https://vldb.gsi.go.jp/sokuchi/surveycalc/main.html
=> feat: NavSatFix publisher for GNSS simulation

Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
I noticed that the Lexus URDF tree is slightly different from what is expected on the [Autoware sensor calibration files](https://github.com/RobotecAI/awsim_sensor_kit_launch/blob/d048e14490f2de9d992cd43b971f5343608c097b/awsim_sensor_kit_description/urdf/sensor_kit.xacro#L27).
1. The VelodyneVLP16 GameObject was placed straight under `sensor_kit_base_link` instead of `velodyne_top_base_link`  GameObject as other sensors in the Prefab.
2. The top velodyne lidar was missing the proper yaw orientation setting.
3. The `velodyne_*_base_link` naming seems to be obsolete in Autoware ([example1](https://github.com/autowarefoundation/sample_sensor_kit_launch/blob/c78006a5c4dd129efa815420989c58da7a3335c5/sample_sensor_kit_launch/launch/lidar.launch.xml#L16), …
=> Fix(prefab): Lexus top velodyne orientation and frame naming

Assets/AWSIM/Scripts/Vehicles/VehicleRos2Input.cs
The PR solves the issue of disappearing scenes in AWSIM. The problem happens in binary AWSIM, it was not observed when working in Unity Editor.
When publishing floating values from Autoware to AWSIM, sometimes NaN values are filled in messages, instead of proper numeric values. This causes the built binary to silently unload the scene, without any logging in Unity `Player.log` file.
To reproduce the issue:
- build the AWSIM binary from Unity Editor
- source the ROS2 workspace containing [autoware_auto_msgs](https://github.com/tier4/autoware_auto_msgs)
- in one terminal publish the GearCommand
```
ros2 topic pub /control/command/gear_cmd  autoware_auto_vehicle_msgs/msg/GearCommand "stamp:
sec: 0
nanosec: 0
command: 2" 
```
- in second terminal publish the ControlCommand
```
ros2 topic pub …
```
=> Fix VehicleRos2Input causing SilentError in binary AWSIM

Assets/AWSIM/Scripts/GeoCoordinate/GeoCoordinate.cs
Regarding the feature added in #340, 
my incorrect fix prevented `worldOriginGeoCoordinate` parameter in Environment.cs from being set from the inspector.
This PR fixes that issue.
Before:
After:
=> fix GeoCoordinate parameter accessibility from inspector

Assets/AWSIM/Scripts/Sensors/LiDAR/PointCloudFormatLibrary.cs, Assets/AWSIM/Scripts/Sensors/LiDAR/RglLidarPublisher.cs, docs/Components/Sensors/LiDARSensor/LiDARSensor/index.md
[INTERNAL TICKET](https://tier4.atlassian.net/browse/RJD-1326)
Change the point cloud format PointXYZIRCEADT introduced in PR https://github.com/tier4/AWSIM/pull/334 to PointXYZIRCAEDT
Current content of the message:
```
[sensor_msgs.msg.PointField(name='x', offset=0, datatype=7, count=1),
sensor_msgs.msg.PointField(name='y', offset=4, datatype=7, count=1),
sensor_msgs.msg.PointField(name='z', offset=8, datatype=7, count=1),
sensor_msgs.msg.PointField(name='intensity', offset=12, datatype=2, count=1),
sensor_msgs.msg.PointField(name='return_type', offset=13, datatype=2, count=1), 
sensor_msgs.msg.PointField(name='channel', offset=14, datatype=4, count=1), 
sensor_msgs.msg.PointField(name='azimuth', offset=16, datatype=7, count=1), 
sensor_msgs.msg.PointField(name='elevation', offset=20, …
```
=> fix(lidar): change point cloud format from PointXYZIRCEADT to PointXYZIRCAEDT

Assets/RGLUnityPlugin/Scripts/LidarRainManager.cs, Assets/RGLUnityPlugin/Scripts/LidarSensor.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNodeSequence.cs
Make adjustments to rain simulation based on multi-return changes on native side.
=> Make adjustments to rain simulation.

Assets/RGLUnityPlugin/Scripts/LidarUdpPublisher.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeTypes.cs, Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNodeSequence.cs
This PR adjust UDP publisher for handling multi-return outputs.
=> Support multi-return modes in UDP publishing

Assets/AWSIM/Scripts/Vehicles/FirstOrderLaggedFloat.cs, Assets/AWSIM/Scripts/Vehicles/FirstOrderLaggedFloat.cs.meta, Assets/AWSIM/Scripts/Vehicles/Vehicle.cs
Add first order delay for AWSIM vehicle control(acceleration and steering).
Since the public property names are unchanged, it is fully compatible with the existing `Vehicle.cs`.
This adds the configurable variable ([s]) to the Vehicle.cs inspector.
When the time constant is set to 0, the delay is disabled and an ideal response is obtained.
As a reminder, these variables are only set during the initialization of the `FirstOrderLaggedFloat` object, so parameter changes during the simulation run are not supported.
=> feat: first order lag for vehicle control

Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/NPCVehicleInternalState.cs, Assets/AWSIM/Scripts/RandomTraffic/NPCVehicle/Steps/NPCVehicleDecisionStep.cs, Assets/AWSIM/Scripts/RandomTraffic/Utils/RandomTrafficUtils.cs
The Random Traffic calculated the distance to the closest traffic light lane in 3D space. The distance did not take the NPC route into account. This can cause situations where NPC stops moving along a lane, since currently it passes a TrafficLight, that it will reach in the future on its route. ([Internal evidence 1](https://tier4.atlassian.net/browse/RJD-1440?focusedCommentId=197496), [Internal evidence 2](https://tier4.atlassian.net/browse/RJD-1452?focusedCommentId=198255))
The PR solves [Internal issue 1](https://tier4.atlassian.net/browse/RJD-1440?focusedCommentId=197496) and [Internal issue 2](https://tier4.atlassian.net/browse/RJD-1452?focusedCommentId=198255)
The PR introduces:
- calculating a distance to next lane using `FollowingLanes` in `NPCVehicleInternalState`
- calculating a …
=> Fix: calculate distance to next lane and intersection using NPC route instead of 3D distance

Assets/Awsim/Scripts/Editor/Usecase/TrafficSimulation/Environments/LaneletLoader/LaneletLoader.cs, Assets/Awsim/Scripts/Editor/Usecase/TrafficSimulation/Environments/LaneletLoader/LaneletLoaderWindow.cs
1. Add field of `Root Game Object` to input hierarchy of generated `TrafficLanes` and `StopLine` ([#4e321a9](https://github.com/tier4/AWSIM/pull/406/commits/4e321a9f22f50874234ad282c68387889b13d8be), [#3beead9](https://github.com/tier4/AWSIM/pull/406/commits/3beead97985404e9b148e1f2a6be48c7ce601b92))
2. Change implementation to give unique name to generated `TrafficLane` ([#3ad8d85](https://github.com/tier4/AWSIM/pull/406/commits/3ad8d859be0c55dbbfcc7484152e89cb314d2122))
a. To avoid error below:
```
VerifyIntegrationEnvironmentElements error: Found repeated child name in the 'TrafficLanes' object: TrafficLane
UnityEngine.Debug:LogError (object)
Awsim.Usecase.TrafficSimulation.TrafficSimulator:verifyIntegrationEnvironmentElements () (at …
```
=> fix: `LaneletLoader` apply v2.0.0
